# Generated by Django 2.2 on 2019-04-15 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190412_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdcprofile',
            name='subscription_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bdcstaff',
            name='added_by',
            field=models.CharField(default=1, editable=False, max_length=4),
        ),
        migrations.AddField(
            model_name='bdcstaff',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
