# Generated by Django 2.2 on 2019-04-15 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20190415_1004'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BdcClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bdc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BdcProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='BdcTranzactions_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_amount', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Amount Sold')),
                ('bought_amount', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Amount Bought')),
                ('client_acct', models.IntegerField(blank=True, verbose_name='Client Account')),
                ('trans_date', models.DateField()),
                ('trans_added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True)),
                ('Updated_by', models.CharField(max_length=5)),
                ('comments', models.TextField(blank=True)),
                ('Bdc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BdcProfile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdctransactions.BdcClient')),
                ('client_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdctransactions.Banks', verbose_name='Client Bank')),
                ('currency_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_bought_currency', to='bdctransactions.Currency', verbose_name='Currency Bought')),
                ('currency_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive_sold_currency', to='bdctransactions.Currency', verbose_name='Currency Sold')),
                ('trans_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BdcTranzactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_amount', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Amount Sold')),
                ('bought_amount', models.DecimalField(decimal_places=4, max_digits=19, verbose_name='Amount Bought')),
                ('client_acct', models.IntegerField(blank=True, verbose_name='Client Account')),
                ('trans_date', models.DateField()),
                ('trans_added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True)),
                ('Updated_by', models.CharField(max_length=5)),
                ('comments', models.TextField(blank=True)),
                ('Bdc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BdcProfile')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdctransactions.BdcClient')),
                ('client_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdctransactions.Banks', verbose_name='Client Bank')),
                ('currency_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_bought_currency', to='bdctransactions.Currency', verbose_name='Currency Bought')),
                ('currency_sold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_sold_currency', to='bdctransactions.Currency', verbose_name='Currency Sold')),
                ('trans_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='bdcclient',
            constraint=models.UniqueConstraint(fields=('bdc_id', 'phone'), name='unique_client'),
        ),
    ]
