# Generated by Django 2.2 on 2019-04-15 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdctransactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdcclient',
            name='acct',
            field=models.CharField(blank=True, max_length=18, verbose_name='client account'),
        ),
        migrations.AddField(
            model_name='bdcclient',
            name='cbank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdctransactions.Banks', verbose_name='Client Bank'),
        ),
    ]
