# Generated by Django 2.2 on 2019-04-15 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdctransactions', '0002_auto_20190415_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bdcclient',
            old_name='cbank',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='bdcclient',
            old_name='bdc_id',
            new_name='bdc',
        ),
        migrations.RenameField(
            model_name='bdctranzactions',
            old_name='Bdc_id',
            new_name='Bdc',
        ),
        migrations.RenameField(
            model_name='bdctranzactions',
            old_name='client_bank',
            new_name='bank',
        ),
        migrations.RenameField(
            model_name='bdctranzactions_archive',
            old_name='Bdc_id',
            new_name='Bdc',
        ),
        migrations.RenameField(
            model_name='bdctranzactions_archive',
            old_name='trans_by',
            new_name='user',
        ),
    ]
